routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

Route::resource('contacts','ContactsController');
Route::resource('states','StatesController');
Route::resource('users','UserController');
Route::resource('companies','CompanyController');
Route::resource('invoice','InvoiceController');
Route::resource('tasks','TaskController');
Route::resource('emails','EmailController');
Route::resource('countries','CountryController');
Route::resource('reports','ReportController');
Route::resource('invoice','InvoiceController');
Route::get('invoiceBorrar/{id}/','InvoiceController@invoiceBorrar')->name('invoiceBorrar');

Route::get('/emails/create', 'EmailController@create');

Route::get('/home', 'HomeController@index');

Route::get('/email', 'TaskController@email');

Route::get('/listusers', 'UserController@index');

Route::get('/security', 'UserController@seguridad');

Route::put('/cambio_clave', 'UserController@cambio_clave');

Route::get('/usuarios/show', 'UserController@show');

Route::get('/reports/companies', 'ReportController@index');

Route::get('/reports/clients', 'ReportController@create');

Route::get('pdfcompany',array('as'=>'pdfcompany','uses'=>'ReportController@uno'));

Route::get('pdfclient',array('as'=>'pdfclient','uses'=>'ReportController@dos'));

app/Task.php
<?php

namespace App;
use App\User;
use App\Company;
use App\State;


use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
	protected $fillable=[
		'company_id','user_id','date_task','description','state_id',
	];	
    public function company(){
    	return $this->belongsTo(Company::class);
    }
    public function state(){
    	return $this->belongsTo(State::class);
    }
    public function user(){
    	return $this->belongsTo(User::class);
    }    
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use Auth;
use Carbon\Carbon;
use App\Company;
use App\User;
use App\State;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Validator;

class TaskController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }    

    public function index()
    {
        if (auth()->user()->rol === "Admin") {
            $tasks = DB::select('
            SELECT
            i.*,
            a.name2,
            b.name,
            c.name3
            FROM
                tasks AS i
            INNER JOIN states AS a
            ON
                i.state_id = a.id
            INNER JOIN users AS b
            ON
                i.user_id = b.id
            INNER JOIN companies AS c
            ON
                i.company_id = c.id
            ');
        }

        if (auth()->user()->rol === "Seller"){
            $este = auth()->user()->id;

            $tasks = DB::select('
            SELECT
            i.*,
            a.name2,
            b.name,
            c.name3
            FROM
                tasks AS i
            INNER JOIN states AS a
            ON
                i.state_id = a.id
            INNER JOIN users AS b
            ON
                i.user_id = b.id
            INNER JOIN companies AS c
            ON
                i.company_id = c.id
            WHERE
                i.user_id = "'.$este.'"    
            ');            
        }  

        // $user = json_decode($response->getBody()->getContents())[0];

        $companys= Company::orderBy('id',"desc")->get();        
        $users= DB::table('users')->orderBy('id',"desc")->get();        
        $states = DB::table('states')->where('type', 'Task')->get();               

        $permiso = new PermisosController;
        $permisos = $permiso->permisos(5);

        if ($permisos) {
            return view('tasks.index', compact('tasks','companys','users','states'));
        } else {
            return redirect('/home')->with('message', '¡Acceso no permitido, contacte al administrador!');
        }  
    }

    public function email()
    {
        return view('tasks.email');
    }    

    public function create()
    {
        if (auth()->user()->rol === "Admin") {
            $tasks = DB::select('
            SELECT
            i.*,
            a.name2,
            b.name,
            c.name3
            FROM
                tasks AS i
            INNER JOIN states AS a
            ON
                i.state_id = a.id
            INNER JOIN users AS b
            ON
                i.user_id = b.id
            INNER JOIN companies AS c
            ON
                i.company_id = c.id
            ');
        }

        if (auth()->user()->rol === "Seller"){
            $este = auth()->user()->id;

            $tasks = DB::select('
            SELECT
            i.*,
            a.name2,
            b.name,
            c.name3
            FROM
                tasks AS i
            INNER JOIN states AS a
            ON
                i.state_id = a.id
            INNER JOIN users AS b
            ON
                i.user_id = b.id
            INNER JOIN companies AS c
            ON
                i.company_id = c.id
            WHERE
                i.user_id = "'.$este.'"    
            ');            
        }  

        // $user = json_decode($response->getBody()->getContents())[0];
        $now=Carbon::now();
        $companys= Company::orderBy('id',"desc")->get();        
        $users= DB::table('users')->orderBy('id',"desc")->get();        
        $states = DB::table('states')->where('type', 'Task')->get();

        return view('tasks.create',compact('companys','now','users','states'));
    }

    public function store(Request $request)
    {
        $tasks=task::create($request->all());
        $tasks->save();

        return redirect()->route('tasks.index')->with('success','Task saved successfully');
    }

    public function show($id)
    {
        $task = Task::findOrFail($id);

        return view('tasks.show', ['task' => $task]);
    }

    public function edit($id)
    {
        if (auth()->user()->rol === "Admin") {
            $tasks = DB::select('
            SELECT
            i.*,
            a.name2,
            b.name,
            c.name3
            FROM
                tasks AS i
            INNER JOIN states AS a
            ON
                i.state_id = a.id
            INNER JOIN users AS b
            ON
                i.user_id = b.id
            INNER JOIN companies AS c
            ON
                i.company_id = c.id
            ');
        }

        if (auth()->user()->rol === "Seller"){
            $este = auth()->user()->id;

            $tasks = DB::select('
            SELECT
            i.*,
            a.name2,
            b.name,
            c.name3
            FROM
                tasks AS i
            INNER JOIN states AS a
            ON
                i.state_id = a.id
            INNER JOIN users AS b
            ON
                i.user_id = b.id
            INNER JOIN companies AS c
            ON
                i.company_id = c.id
            WHERE
                i.user_id = "'.$este.'"    
            ');            
        }  

        // $user = json_decode($response->getBody()->getContents())[0];
        $now=Carbon::now();
        $task=Task::findOrFail($id);
        $companys= Company::orderBy('id',"desc")->get();        
        $users= DB::table('users')->orderBy('id',"desc")->get();        
        $states = DB::table('states')->where('type', 'Task')->get();

        return view('tasks.edit',compact('tasks','now','companys','states','task','users'));
    }

    public function update(Request $request, $id)
    {
        $task=Task::findOrFail($id);
        $task->update($request->all());
        $task->save();

        return redirect()->route('tasks.index')->with('success','Task successfully edited');
    }

    public function destroy($id)
    {
        $task = Task::findOrFail($id);
        $task->delete();

        return response()->json($task);
    }
}

resources/views/tasks/create.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

</head>

<body>
    <div class="col-md-12">
        <h2>New Task</h2>
        <br />
        <div class="panel panel-primary panel">
            <div class="panel-heading">
                <ul>
                    <li><i class="fa fa-file-text-o"></i> All the current Tasks</li>
                </ul>
            </div>
        
            <div class="panel-body">
              <form action="{{route('tasks.store')}}" id="form-insert" enctype="multipart/form-data" method="POST"> 
                {{csrf_field()}}
                <div class="row">
                        <div class="form-group col-sm-6">
                            <label>Company / Client</label>
                            <select name="company_id" class="select2 form-control"  style="width: 100%;" required>
                                <option value="">Select Company/Client</option>
                                 @foreach($companys as $c)
                                <option value="{{$c->id}}">{{$c->name3}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('company_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('company_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        @if (auth()->user()->rol === "Admin")
                        <div class="form-group col-sm-6">
                            <label>Responsable</label>
                            <select name="user_id" class="select2 form-control"  style="width: 100%;" required>
                                <option value="">Select Responsable</option>
                                 @foreach($users as $u)
                                <option value="{{$u->id}}">{{$u->name}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('user_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('user_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        @else
                        <div class="form-group col-sm-6">
                            <label>Responsable</label>
                            <select name="user_id" class="select2 form-control"  style="width: 100%;" required>
                                <option value="">Select Responsable</option>
                                <option value="{{auth()->user()->id}}">{{auth()->user()->name}}</option>
                            </select>
                            @if($errors->has('user_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('user_id')}}</strong>
                            </span>
                            @endif
                        </div>                        
                        @endif                        
                    
                </div>

                <div class="row">
                    <div class="form-group col-sm-6">
                        <label for="">Date</label>
                        <input type="date" name="date_task" class="form-control" value="{{$now->format('Y-m-d')}}" min="{{$now->format('Y-m-d')}}" required>
                       @if($errors->has('date_task'))
                            <span class="text-danger">
                                <strong>{{$errors->first('date_task')}}</strong>
                            </span>
                       @endif
                    </div>

                    <div class="form-group col-sm-6">
                    <label for="">Description</label>
                    <textarea class="form-control" name="description" placeholder="Description" required></textarea>
                    @if($errors->has('description'))
                            <span class="text-danger">
                                <strong>{{$errors->first('description')}}</strong>
                            </span>
                    @endif
                    </div>
                </div>
                

                <div class="row">
                    <div class="form-group col-sm-6">
                    <label for="">State</label>
                    <select name="state_id" class="select2 form-control" style="width: 100%;" required>
                        <option value="">Select State</option>
                        @foreach($states as $state)
                            <option value="{{$state->id}}">{{$state->name2}}</option>
                        @endforeach
                    </select>
                   @if($errors->has('state_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('state_id')}}</strong>
                            </span>
                   @endif
                    </div>
                </div>
                
                <center>
                  <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-primary add">
                            <span id="" class='glyphicon glyphicon-check'></span> Add
                        </button>
                        <a href="{{route('tasks.index')}}" class="btn btn-danger">
                            <span class='glyphicon glyphicon-remove'></span> Regresar
                        </a>
                  </div>
                </center>  
                </form>
              
            </div><!-- /.panel-body -->
        </div><!-- /.panel panel-default -->
    </div><!-- /.col-md-8 -->


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>


</body>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/tasks/edit.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

</head>

<body>
    <div class="col-md-12">
        <h2> Edit Task</h2>
        <br />
        <div class="panel panel-primary panel">
            <div class="panel-heading">
                <ul>
                    <li><i class="fa fa-file-text-o"></i> All the current Tasks</li>
                </ul>
            </div>
        
            <div class="panel-body">
              <form action="{{route('tasks.update',$task->id)}}" id="form-insert" enctype="multipart/form-data" method="POST"> 
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="row">
                        <div class="form-group col-sm-6">
                            <label>Company / Client</label>
                            <select id="company_id" name="company_id" class="form-control"  style="width: 100%;">
                                <option value="">Select Company/Client</option>
                                 @foreach($companys as $c)
                                <option value="{{$c->id}}" {{$task->company_id ? 'selected' : ''}}>{{$c->name3}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('company_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('company_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        @if (auth()->user()->rol === "Admin")                        
                        <div class="form-group col-sm-6">
                            <label>Responsable</label>
                            <select id="user_id" name="user_id" class="form-control"  style="width: 100%;">
                                <option value="">Select Responsable</option>
                                 @foreach($users as $c)
                                <option value="{{$c->id}}" {{$task->user_id ? 'selected' : ''}}>{{$c->name}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('invoice_number'))
                            <span class="text-danger">
                                <strong>{{$errors->first('invoice_number')}}</strong>
                            </span>
                            @endif
                        </div>
                        @else
                        <div class="form-group col-sm-6">
                            <label>Responsable</label>
                            <select id="user_id" name="user_id" class="form-control"  style="width: 100%;">
                                <option value="{{auth()->user()->id}}">{{auth()->user()->name}}</option>
                            </select>
                            @if($errors->has('invoice_number'))
                            <span class="text-danger">
                                <strong>{{$errors->first('invoice_number')}}</strong>
                            </span>
                            @endif
                        </div>                        
                        @endif                    
                </div>

                <div class="row">
                    <div class="form-group col-sm-6">
                        <label for="">Date</label>
                        <input type="date" name="date_task" class="form-control" value="{{$now->format('Y-m-d')}}" value="{{$task->date_task}}">
                       @if($errors->has('date_task'))
                            <span class="text-danger">
                                <strong>{{$errors->first('date_task')}}</strong>
                            </span>
                       @endif
                    </div>
                    <div class="form-group col-sm-6">
                    <label for="">Description</label>
                    <textarea class="form-control" name="description" placeholder="Description" required>{{$task->description}}</textarea>
                    @if($errors->has('description'))
                            <span class="text-danger">
                                <strong>{{$errors->first('description')}}</strong>
                            </span>
                    @endif
                    </div>
                </div>
                

                <div class="row">
                    <div class="form-group col-sm-6">
                    <label for="">State</label>
                    <select  id="state_id" name="state_id" class="select2 form-control" style="width: 100%;">
                        <option value="">Select State</option>
                        @foreach($states as $state)
                            <option value="{{$state->id}}" {{$task->state_id ? 'selected' : ''}}>{{$state->name2}}</option>
                        @endforeach
                    </select>
                   @if($errors->has('state_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('state_id')}}</strong>
                            </span>
                   @endif
                    </div>
                </div>

                <center>
                  <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-primary add">
                            <span id="" class='glyphicon glyphicon-check'></span> Add
                        </button>
                        <a href="{{route('tasks.index')}}" class="btn btn-danger">
                            <span class='glyphicon glyphicon-remove'></span> Regresar
                        </a>
                  </div>
                </center>  
                </form>
              
            </div><!-- /.panel-body -->
        </div><!-- /.panel panel-default -->
    </div><!-- /.col-md-8 -->


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>


</body>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/tasks/email.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

</head>

<style>
#add_status > .select2-choice{
     background-color:blue;
}	
</style>

<body>
    <div class="col-md-12">
        <h2>Tasks</h2>
        <br />

        <iframe src="http://localhost/formulario-ajax/index.php" width="1300" height="600" style="border: 0px;"></iframe>    
    </div><!-- /.col-md-8 -->



    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>


</body>

        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/tasks/emailindex.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.css">

<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>

<header class="main-header"><meta http-equiv="Content-Type" content="text/html; charset=euc-jp">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="height:1000px">
            </head>

            <body>
              <section class="content">
<div class="col-md-12">
                    <h2>Mails</h2>
                    <br />
                        <a href="emails/create" class="add-modal btnn btn btn-default"><i class="fa fa-plus"></i> Send a Mail</a>
                    <div class="panel panel-primary panel">
                        <div class="panel-heading">
                            <ul>
                                <li><i class="fa fa-file-text-o"></i> All the current Mails</li>
                            </ul>
                        </div>
                    
                        <div class="panel-body">
                                <table class="table table-responsive table-striped table-bordered table-hover" id="mytable">
                                    <thead>
                                        <tr>
                                            <th valign="middle">#</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Date</th>
                                            <th>Phone</th>
                                            <th colspan="2">Actions</th>
                                        </tr>
                                        {{ csrf_field() }}
                                    </thead>
                                    <tbody>
                                        @foreach($mail as $indexKey => $usu)
                                            <tr class="item{{$usu->id}}">
                                                <td class="col1">{{ $indexKey+1 }}</td>
                                                <td>{{$usu->ab_name}}</td>
                                                <td>
                                                    {{$usu->ab_email}}
                                                </td>
                                                <td>
                                                    {{$usu->ab_date}}
                                                </td>
                                                <td>
                                                    {{$usu->ab_phone}}
                                                </td>

                                <td>
                                  <a href="{{ route('emails.show', $usu->id) }}" class="btn btn-primary" data-toggle="tooltip" title="Show"><i class="fa fa-eye"></i>

                                  </a>
                                </td>  
                                
<!-- s -->  

                                <td>
                                  <form action="{{ route('emails.destroy', $usu->id) }}" method="post">
                                    <input name="_method" type="hidden" value="DELETE">
                                      <input required="true" type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button type="submit" onclick="if(!confirm('¿Desea eliminar al analista?'))event.preventDefault();" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i class="fa fa-trash"></i></button>

                                  </form>
                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                        </div><!-- /.panel-body -->
                    </div><!-- /.panel panel-default -->
                </div><!-- /.col-md-8 -->
            </section><!-- /.content -->

                <!-- jQuery -->
                <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>


            </body>
        </div>  
    <!-- /.content-wrapper -->
        <script>
            $(document).ready(function() {
                $('#mytable').dataTable();
            } );    
        </script> 
@include('layouts.footer')

resources/views/tasks/emailsee.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            </head>

            <body>

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">

                            <hr>
                            <a class="btn btn-default btn-teal btn-responsive" style="float: right;" href="javascript:history.back(1)" title="Regresar"><i class="fa fa-mail-reply-all fa-lg"></i></a><br>                 
                            <div class="panel panel-default">
                                <center><div class="panel-heading"><h4>User</h4></div></center>
                                <div class="panel-body">
                    <form method="post" action=" {{ url('/emails/') }}/{{ $mail->id }}">
                        <input name="_method" type="hidden" value="PUT">
                        <input required="true" type="hidden" name="_token" value="{{ csrf_token() }}">

                        <div class="form-group col-xs-6">
                            <label for="name" class="col-md-4 control-label">Name</label>

                                <input id="name" type="text" class="form-control" placeholder="Indique el nombre" name="name" value="{{ $mail->ab_name }}" required autofocus disabled>
                        </div>

                        <div class="form-group col-xs-6">
                            <label for="email" class="col-md-4 control-label">E-mail</label>

                                <input id="email" type="email" class="form-control" placeholder="Indique el correo electrónico" name="email" value="{{ $mail->ab_email }}" required disabled>

                        </div>  

                        <div class="form-group col-xs-6">
                            <label for="name" class="col-md-4 control-label">Phone</label>

                                <input id="name" type="text" class="form-control" placeholder="Indique el nombre" name="name" value="{{ $mail->ab_phone }}" required autofocus disabled>
                        </div>

                        <div class="form-group col-xs-6">
                            <label for="email" class="col-md-4 control-label">Message</label>

                                <input id="email" type="email" class="form-control" placeholder="Indique el correo electrónico" name="email" value="{{ $mail->ab_message }}" required disabled>

                        </div>                            
          

                            </div> 
                               <center class="col-xs-offset-3 col-xs-6">
                                      <button data-toggle="tooltip" title="Regresar" type="reset" onClick="javascript:history.go(-1);" class="btn btn-refresh margin glyphicon glyphicon-arrow-left"></button>
                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- jQuery -->
                <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

            </body>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')