routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

Route::resource('contacts','ContactsController');
Route::resource('states','StatesController');
Route::resource('users','UserController');
Route::resource('companies','CompanyController');
Route::resource('invoice','InvoiceController');
Route::resource('tasks','TaskController');
Route::resource('emails','EmailController');
Route::resource('countries','CountryController');
Route::resource('reports','ReportController');
Route::resource('invoice','InvoiceController');
Route::get('invoiceBorrar/{id}/','InvoiceController@invoiceBorrar')->name('invoiceBorrar');

Route::get('/emails/create', 'EmailController@create');

Route::get('/home', 'HomeController@index');

Route::get('/email', 'TaskController@email');

Route::get('/listusers', 'UserController@index');

Route::get('/security', 'UserController@seguridad');

Route::put('/cambio_clave', 'UserController@cambio_clave');

Route::get('/usuarios/show', 'UserController@show');

Route::get('/reports/companies', 'ReportController@index');

Route::get('/reports/clients', 'ReportController@create');

Route::get('pdfcompany',array('as'=>'pdfcompany','uses'=>'ReportController@uno'));

Route::get('pdfclient',array('as'=>'pdfclient','uses'=>'ReportController@dos'));

app/Invoice.php
<?php

namespace App;
use App\Company;
use App\State;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{

	protected $fillable=[
		'company_id','state_id','invoice_number','date_issue','date_expiration','rode','file',
	];
    public function company(){
    	return $this->belongsTo(Company::class);
    }

    public function state(){
    	return $this->belongsTo(State::class);
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Invoice;
use App\User;
use App\Company;
use App\State;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use App\Http\Requests\InvoiceStoreRequest;
use App\Http\Requests\InvoiceUpdateRequest;


class InvoiceController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }


    public function index()
    {

        $invoices = DB::select('
        SELECT
        i.*,
        a.name2,
        c.name3
        FROM
            invoices AS i
        INNER JOIN states AS a
        ON
            i.state_id = a.id
        INNER JOIN companies AS c
        ON
            i.company_id = c.id
            '); 

        $now=Carbon::now();
        $companies = Company::orderBy('id','ASC')->get();
        $states = DB::table('states')->where('type', 'Invoice')->get();

        $permiso = new PermisosController;
        $permisos = $permiso->permisos(4);

        if ($permisos) {
            return view('invoices.index', compact('companies','now','invoices','states'));
        } else {
            return redirect('/home')->with('message', '¡Acceso no permitido, contacte al administrador!');
        }         
    }

    public function create(){
        $now=Carbon::now();
        $companies = Company::orderBy('id','ASC')->get();
        $states = DB::table('states')->where('type', 'Invoice')->get();
        return view('invoices.create',compact('companies','now','states'));
    }

    public function store(InvoiceStoreRequest $request)
    {
        $invoice=Invoice::create($request->all());
        
        if($request->file('file')){
            $file = $request->file('file');
            $name = $file->getClientOriginalName();
            $path = public_path() .'/img/';    
            $img='img/'.$name;
            $file->move($path,$name);            
            $invoice->fill(['file'=> asset($img)])->save();
        }
       

        return redirect()->route('invoice.index')->with('success','Invoice guardado con exito');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $invoice=Invoice::findOrFail($id);
        $now=Carbon::now();
        $companies = Company::orderBy('id','ASC')->get();
        $states = DB::table('states')->where('type', 'Invoice')->get();
        return view('invoices.edit',compact('invoice','now','companies','states'));
    }

    public function update(InvoiceUpdateRequest $request, $id)
    {

        $invoice=Invoice::findOrFail($id);
        $invoice->update($request->all());
        
         if($request->file('file')){
            $file = $request->file('file');
            $name = $file->getClientOriginalName();
            $path = public_path() .'/img/';    
            $img='img/'.$name;
            $file->move($path,$name);            
            $invoice->fill(['file'=> asset($img)])->save();
        }

        return redirect()->route('invoice.index')->with('success','Invoice editado con exito');
    }

    public function destroy($id)
    {
     return view('invoices.create');
    }

    public function invoiceBorrar($id){
        Invoice::findOrFail($id)->delete();
        return redirect()->route('invoice.index')->with('success','Invoice eliminada con exito');
    }
}

resources/views/invoices/create.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

</head>

<body>
    <div class="col-md-12">
        <h2>New Invoice</h2>
        <br />
        <div class="panel panel-primary panel">
            <div class="panel-heading">
                <ul>
                    <li><i class="fa fa-file-text-o"></i> All the current Invoice</li>
                </ul>
            </div>
        
            <div class="panel-body">
              <form action="{{route('invoice.store')}}" id="form-insert" enctype="multipart/form-data" method="POST"> 
                {{csrf_field()}}
                <div class="row">
                        <div class="form-group col-sm-6">
                            <label>Company / Client</label>
                            <select id="company_id" name="company_id" class="select2 form-control"  style="width: 100%;">
                                <option value="">Select Company/Client</option>
                                 @foreach($companies as $c)
                                <option value="{{$c->id}}">{{$c->name3}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('company_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('company_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group col-sm-6">
                            <label>N° Invoice</label>
                            <input type="text" id="invoice_number" name="invoice_number" class="form-control" placeholder="#2322334-23">
                            @if($errors->has('invoice_number'))
                            <span class="text-danger">
                                <strong>{{$errors->first('invoice_number')}}</strong>
                            </span>
                            @endif
                        </div>                    
                </div>

                <div class="row">
                    <div class="form-group col-sm-6">
                        <label for="">Date of issue</label>
                        <input type="date" id="date_issue" name="date_issue" class="form-control" value="{{$now->format('Y-m-d')}}">
                       @if($errors->has('date_issue'))
                            <span class="text-danger">
                                <strong>{{$errors->first('date_issue')}}</strong>
                            </span>
                       @endif
                    </div>
                    <div class="form-group col-sm-6">
                    <label for="">Date Expiration</label>
                    <input type="date" id="date_expiration" name="date_expiration" class="form-control">
                    @if($errors->has('date_expiration'))
                            <span class="text-danger">
                                <strong>{{$errors->first('date_expiration')}}</strong>
                            </span>
                    @endif
                    </div>
                </div>
                

                <div class="row">
                    <div class="form-group col-sm-6">
                    <label for="">State</label>
                    <select  id="state_id" name="state_id" class="select2 form-control" style="width: 100%;">
                        <option value="">Select State</option>
                        @foreach($states as $state)
                            <option value="{{$state->id}}">{{$state->name2}}</option>
                        @endforeach
                    </select>
                   @if($errors->has('state_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('state_id')}}</strong>
                            </span>
                   @endif
                    </div>
                    <div class="form-group col-sm-6">
                    <label for="">Rode</label>
                    <input type="text" id="rode" name="rode" class="form-control" placeholder="2000.00">
                    @if($errors->has('rode'))
                            <span class="text-danger">
                                <strong>{{$errors->first('rode')}}</strong>
                            </span>
                    @endif
                    </div>
                </div>
                <hr>
                
                <div class="col-sm-12">
                  <div class="form-group image">
                    <input  name="file" type="file"  data-preview-file-type="any" class="file"  id="file">
                  </div>
                  @if($errors->has('file'))
                     <span class="text-danger">
                        <strong>{{$errors->first('file')}}</strong>
                    </span>
                @endif
                  
                </div>
                <center>
                  <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-primary add">
                            <span id="" class='glyphicon glyphicon-check'></span> Add
                        </button>
                        <a href="{{route('invoice.index')}}" class="btn btn-danger">
                            <span class='glyphicon glyphicon-remove'></span> Regresar
                        </a>
                  </div>
                </center>  
                </form>
              
            </div><!-- /.panel-body -->
        </div><!-- /.panel panel-default -->
    </div><!-- /.col-md-8 -->


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>


</body>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/invoices/edit.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

</head>

<body>
    <div class="col-md-12">
        <h2> Edit Invoice</h2>
        <br />
        <div class="panel panel-primary panel">
            <div class="panel-heading">
                <ul>
                    <li><i class="fa fa-file-text-o"></i> All the current Invoice</li>
                </ul>
            </div>
        
            <div class="panel-body">
              <form action="{{route('invoice.update',$invoice->id)}}" id="form-insert" enctype="multipart/form-data" method="POST"> 
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="row">
                        <div class="form-group col-sm-6">
                            <label>Company / Client</label>
                            <select id="company_id" name="company_id" class="select2 form-control"  style="width: 100%;">
                                <option value="">Select Company/Client</option>
                                 @foreach($companies as $c)
                                <option value="{{$c->id}}" {{$invoice->company_id ? 'selected' : ''}}>{{$c->name3}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('company_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('company_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group col-sm-6">
                            <label>N° Invoice</label>
                            <input type="text" id="invoice_number" name="invoice_number" class="form-control" placeholder="#2322334-23" value="{{$invoice->invoice_number}}">
                            @if($errors->has('invoice_number'))
                            <span class="text-danger">
                                <strong>{{$errors->first('invoice_number')}}</strong>
                            </span>
                            @endif
                        </div>                    
                </div>

                <div class="row">
                    <div class="form-group col-sm-6">
                        <label for="">Date of issue</label>
                        <input type="date" id="date_issue" name="date_issue" class="form-control" value="{{$now->format('Y-m-d')}}" value="{{$invoice->date_issue}}">
                       @if($errors->has('date_issue'))
                            <span class="text-danger">
                                <strong>{{$errors->first('date_issue')}}</strong>
                            </span>
                       @endif
                    </div>
                    <div class="form-group col-sm-6">
                    <label for="">Date Expiration</label>
                    <input type="date" id="date_expiration" name="date_expiration" class="form-control" value="{{$invoice->date_expiration}}">
                    @if($errors->has('date_expiration'))
                            <span class="text-danger">
                                <strong>{{$errors->first('date_expiration')}}</strong>
                            </span>
                    @endif
                    </div>
                </div>
                

                <div class="row">
                    <div class="form-group col-sm-6">
                    <label for="">State</label>
                    <select  id="state_id" name="state_id" class="select2 form-control" style="width: 100%;">
                        <option value="">Select State</option>
                        @foreach($states as $state)
                            <option value="{{$state->id}}" {{$invoice->state_id ? 'selected' : ''}}>{{$state->name2}}</option>
                        @endforeach
                    </select>
                   @if($errors->has('state_id'))
                            <span class="text-danger">
                                <strong>{{$errors->first('state_id')}}</strong>
                            </span>
                   @endif
                    </div>
                    <div class="form-group col-sm-6">
                    <label for="">Rode</label>
                    <input type="text" id="rode" name="rode" class="form-control" placeholder="2000.00" value="{{$invoice->rode}}">
                    @if($errors->has('rode'))
                            <span class="text-danger">
                                <strong>{{$errors->first('rode')}}</strong>
                            </span>
                    @endif
                    </div>
                </div>
                 <div class="col-md-12">
                    <label for="">Archivo Actual</label>
                    <a href="#" onclick="archivo('{{$invoice->file}}')" id="file" >{{$invoice->file}}</a>
                </div>
                <hr>
                
                <div class="col-sm-12">
                  <div class="form-group image">
                    <input  name="file" type="file"  data-preview-file-type="any" class="file"  id="file" value="{{$invoice->file}}">
                  </div>
                  @if($errors->has('file'))
                     <span class="text-danger">
                        <strong>{{$errors->first('file')}}</strong>
                    </span>
                @endif
                  
                </div>

                <center>

                  <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-primary add">
                            <span id="" class='glyphicon glyphicon-check'></span> Add
                        </button>
                        <a href="{{route('invoice.index')}}" class="btn btn-danger">
                            <span class='glyphicon glyphicon-remove'></span> Regresar
                        </a>
                  </div>
                </center>  
                </form>
              
            </div><!-- /.panel-body -->
        </div><!-- /.panel panel-default -->
    </div><!-- /.col-md-8 -->


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>


</body>
<script type="text/javascript">
            function archivo(archivo){
                window.open(archivo,"width=200","height=100");
             }
</script>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/invoices/index.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper" style="height: auto;">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="height: 1000px;">

</head>

<body>
    <div class="col-md-12">
        <h2>Invoice</h2>
        <br />
         @if(session('success'))
        <div class="col-md-12" style="margin-bottom: 10px;">
            <div class="alert alert-success">{{session('success')}}</div>
        </div>
        @endif
        <div class="col-md-12" style="display: flex;justify-content: flex-end;">
            <a href="{{route('invoice.create')}}" class="btn btn-default"><i class="fa fa-plus"></i> Add a Invoice</a>
        </div>
        <div class="panel panel-primary panel">
            <div class="panel-heading">
                <ul>
                    <li><i class="fa fa-file-text-o"></i> All the current Invoice</li>
                </ul>
            </div>
        
            <div class="panel-body">
                <div class="responsive">
                    <table class="table table-striped table-bordered table-hover" id="mytable">
                        <thead>
                            <tr>
                                <th>Invoice Number</th>
                                <th>Company</th>
                                <th>State</th>
                                <th>Rode</th>
                                <th>Actions</th>
                            </tr>
                            {{ csrf_field() }}
                        </thead>
                        <tbody>
                            @foreach($invoices as $invoi)
                                <tr class="item{{$invoi->id}}">
                                    <td>
                                    #{{$invoi->invoice_number}}
                                    </td>
                                    <td>
                                        {{$invoi->name3}}
                                    </td>
                                    <td>
                                        {{$invoi->name2}}
                                    </td>                         
                                    <td>
                                        {{$invoi->rode}}
                                    </td>
                                    <td>
                                      <button class="show-modal btn btn-primary" data-id="{{$invoi->id}}" data-invoice_number="{{$invoi->invoice_number}}" data-company="{{$invoi->name3}}" data-di="{{$invoi->date_issue}}" data-de="{{$invoi->date_expiration}}" data-rode="{{$invoi->rode}}" data-state="{{$invoi->name2}}" data-file="{{$invoi->file}}">
                                        <span class="glyphicon glyphicon-eye-open"></span> Show</button>
                                        <a class="btn btn-warning" href="{{route('invoice.edit',$invoi->id)}}">
                                        <span class="glyphicon glyphicon-edit"></span> Edit</a>
                                        <a class="btn btn-danger" href="{{route('invoiceBorrar',$invoi->id)}}" onclick="return confirm('Seguro desea eliminar esta factura la factura?')">
                                        <span class="glyphicon glyphicon-trash"></span> Delete</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                    
            </div><!-- /.panel-body -->
        </div><!-- /.panel panel-default -->
    </div><!-- /.col-md-8 -->


    <!-- Modal form to show a post -->
    <div id="showModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label class="control-label">Company / Client</label>
                            <input type="text" id="show_company" class="form-control" disabled>
                        </div>
                        <div class="form-group col-sm-6">
                            <label>N° Invoice</label>
                            <input type="text" id="show_invoice_number" class="form-control" disabled>
                        </div>                    
                </div>

                <div class="row">
                    <div class="form-group col-sm-6">
                        <label for="">Date of issue</label>
                        <input type="date" id="show_date_issue" class="form-control" disabled>
                    </div>
                    <div class="form-group col-sm-6">
                    <label for="">Date Expiration</label>
                    <input type="date" id="show_date_expiration" class="form-control" disabled>
                    </div> 
            </div>

             <div class="row">
                    <div class="form-group col-sm-6">
                    <label for="">State</label>
                    <input type="text" id="show_state" class="form-control" disabled>
                    </div>
                    <div class="form-group col-sm-6">
                    <label for="">Rode</label>
                    <input type="text" id="show_rode" class="form-control" disabled>
                    </div>
                </div>

              <a href="#" onclick="" id="file" ></a>

             <div class="modal-footer">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">
                            <span class='glyphicon glyphicon-remove'></span> Close
                        </button>
            </div>
        </div>
    </div>
</div>


<div id="deleteModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label class="control-label">ID</label>
                            <input type="text" id="delete_id" class="form-control" disabled>
                        </div>
                        <div class="form-group col-sm-6">
                            <label>N° Invoice</label>
                            <input type="text" id="delete_invoice_number" class="form-control" disabled>
                        </div>                    
                </div>


             <div class="modal-footer">
                        <button type="button" class="btn btn-danger delete" data-dismiss="modal">
                                    <span id="" class='glyphicon glyphicon-trash'></span> Delete
                                </button>
                        <button type="button" class="btn btn-warning" data-dismiss="modal">
                            <span class='glyphicon glyphicon-remove'></span> Close
                        </button>
            </div>
        </div>
    </div>
</div>


    <!-- Modal form to edit a form -->
      

@include('layouts.footer')
<!-- AJAX CRUD operations -->
    <script type="text/javascript">
                    
        // Show a company
                    $(document).on('click', '.show-modal', function() {
                        $('.modal-title').text('Show');
                        $('#show_company').val($(this).data('company'));
                        $('#show_invoice_number').val($(this).data('invoice_number'));
                        $('#show_date_issue').val($(this).data('di'));
                        $('#show_date_expiration').val($(this).data('de'));
                        $('#show_rode').val($(this).data('rode'));
                        $('#show_state').val($(this).data('state'));
                        $('#file').attr("onclick","archivo('"+$(this).data('file')+"')");
                        $('#file').html($(this).data('file'));
                        $('#showModal').modal('show');
                    });
        
    </script>

    <script>
        function archivo(archivo){
                window.open(archivo,"width=200","height=100");
        }
    </script>

</body>

        </div>  