routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', function () {
    return view('welcome');
});

Route::resource('contacts','ContactsController');
Route::resource('states','StatesController');
Route::resource('users','UserController');
Route::resource('companies','CompanyController');
Route::resource('invoice','InvoiceController');
Route::resource('tasks','TaskController');
Route::resource('emails','EmailController');
Route::resource('countries','CountryController');
Route::resource('reports','ReportController');
Route::resource('invoice','InvoiceController');
Route::get('invoiceBorrar/{id}/','InvoiceController@invoiceBorrar')->name('invoiceBorrar');

Route::get('/emails/create', 'EmailController@create');

Route::get('/home', 'HomeController@index');

Route::get('/email', 'TaskController@email');

Route::get('/listusers', 'UserController@index');

Route::get('/security', 'UserController@seguridad');

Route::put('/cambio_clave', 'UserController@cambio_clave');

Route::get('/usuarios/show', 'UserController@show');

Route::get('/reports/companies', 'ReportController@index');

Route::get('/reports/clients', 'ReportController@create');

Route::get('pdfcompany',array('as'=>'pdfcompany','uses'=>'ReportController@uno'));

Route::get('pdfclient',array('as'=>'pdfclient','uses'=>'ReportController@dos'));

resources/views/usuarios/create.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            </head>

            <body>

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <hr>
                            <a class="btn btn-default btn-teal btn-responsive" style="float: right;" href="javascript:history.back(1)" title="Regresar"><i class="fa fa-mail-reply-all fa-lg"></i></a><br>
                            <div class="panel panel-default">
                                <center><div class="panel-heading"><h4>Add User</h4></div></center>
                                <div class="panel-body">
                                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/users/') }}">
                                        {{ csrf_field() }}

                                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                            <label for="name" class="col-md-4 control-label">Name</label>

                                            <div class="col-md-6">
                                                <input id="name" type="text" class="form-control" placeholder="Indique el nombre" name="name" value="{{ old('name') }}" required autofocus>

                                                @if ($errors->has('name'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                            <label for="email" class="col-md-4 control-label">E-mail</label>

                                            <div class="col-md-6">
                                                <input id="email" type="email" class="form-control" placeholder="Indique el correo electrónico" name="email" value="{{ old('email') }}" required>

                                                @if ($errors->has('email'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('email') }}</strong>
                                                </span>
                                                @endif
                                            </div>
                                        </div>
                             

                                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                            <label for="password" class="col-md-4 control-label">Password</label>

                                            <div class="col-md-6">
                                                <input id="password" type="password" placeholder="Contraseña" class="form-control" name="password" required>

                                                @if ($errors->has('password'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('password') }}</strong>
                                                </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                                            <div class="col-md-6">
                                                <input id="password-confirm" type="password" placeholder="Repita su contraseña" class="form-control" name="password_confirmation" required>
                                            </div>
                                        </div>

                                        <div class="col-md-10 col-md-offset-2">
                                          <h3>Permits</h3>
                                          <p>Section the functions to which the user will have access</p>            
                                          <table class="table">
                                            <thead>
                                              <tr>
                                                <th>Module / Permission</th>
                                                <th>Enable or Disable</th>
                                              </tr>
                                            </thead>
                                            <tbody>
                                            @foreach ($modules as $mod)
                                              <tr>
                                                <td>{{ ($mod->nombre) }}</td>
                                                <td>
                                                <div class="checkbox">
                                                    <label>
                                                        <input type="checkbox" 
                                                               value="{{ ($mod->id) }}" 
                                                               name="modules[]"  
                                                        ></label>
                                                </div>
                
                                                </td>
                                              </tr>
                                            @endforeach
                                            </tbody>
                                          </table>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-6 col-md-offset-4">
                                                <center>                                      
                                                    <button data-toggle="tooltip" title="Guardar" type="submit" class="btn btn-guardar margin glyphicon glyphicon-floppy-disk" name="agregar"></button>
                                                </center>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- jQuery -->
                <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

            </body>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/usuarios/edit.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            </head>

            <body>

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <hr>
                            <a class="btn btn-default btn-teal btn-responsive" style="float: right;" href="javascript:history.back(1)" title="Regresar"><i class="fa fa-mail-reply-all fa-lg"></i></a><br>            
                            <div class="panel panel-default">
                                <center><div class="panel-heading"><h4>Edit User</h4></div></center>                                
                                <div class="panel-body">
                                    <form method="post" action=" {{ url('/users/') }}/{{ $usuarios->id }}" class="form-horizontal" role="form">
                                     <input name="_method" type="hidden" value="PUT">
                                     <input required="true" type="hidden" name="_token" value="{{ csrf_token() }}">

                                     <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label for="name" class="col-md-4 control-label">Name</label>

                                        <div class="col-md-6">
                                            <input id="name" type="text" class="form-control" placeholder="Indique el nombre" name="name" value="{{ old('name') }}{{ $usuarios->name }}" required autofocus>

                                            @if ($errors->has('name'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('name') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                        <label for="email" class="col-md-4 control-label">E-mail</label>

                                        <div class="col-md-6">
                                            <input id="email" type="email" class="form-control" placeholder="Indique el correo electrónico" name="email" value="{{ old('email') }}{{ $usuarios->email }}" required>

                                            @if ($errors->has('email'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('email') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                        <label for="password" class="col-md-4 control-label">Password</label>

                                        <div class="col-md-6">
                                            <input id="password" type="password" class="form-control" placeholder="Indique el correo electrónico" name="password" value="{{ old('password') }}{{ $usuarios->password }}" required readonly>

                                            @if ($errors->has('password'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('password') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                    </div>                                    
                                   

                                    <div class="col-md-10 col-md-offset-2">
                                          <h3>Permits</h3>
                                          <p>Section the functions to which the user will have access</p>            
                                          <table class="table">
                                            <thead>
                                              <tr>
                                                <th>Module / Permission</th>
                                                <th>Habilitar</th>
                                              </tr>
                                            </thead>
                                            <tbody>
                                            @foreach ($modules as $mod)
                                              <tr>
                                                <td>{{ ($mod->nombre) }}</td>
                                                <td>
                                                <div class="checkbox">
                                                    <label>
                                                        <input type="checkbox" 
                                                               value="{{ ($mod->id) }}" 
                                                               name="modules[]"
                                                                @if (in_array($mod->id, $checked ))
                                                                    {{ 'checked' }}
                                                                @endif  
                                                        ></label>
                                                </div>
                                                </td>
                                              </tr>
                                            @endforeach
                                            </tbody>
                                          </table>
                                        </div>

                                    <div class="form-group">
                                        <div class="col-md-6 col-md-offset-4">
                                            <center>                                      
                                                <button data-toggle="tooltip" title="Guardar" type="submit" class="btn btn-guardar margin glyphicon glyphicon-floppy-disk" name="agregar"></button>
                                            </center>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

                <!-- jQuery -->
                <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

            </body>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/usuarios/index.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.css">

    <script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>    

    <header class="main-header">
        @include('layouts.header')
    </header>

    @include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
    </head>

    <body>
      <section class="content">
        <div class="col-md-12">
            <h2>Users</h2>
            <br />
            <a href="users/create" class="add-modal btnn btn btn-default"><i class="fa fa-plus"></i> Add a User</a>
            <div class="panel panel-primary panel">
                <div class="panel-heading">
                    <ul>
                        <li><i class="fa fa-file-text-o"></i> All the current Users</li>
                    </ul>
                </div>
                
                <div class="panel-body">
                    <table class="table table-responsive table-striped table-bordered table-hover" id="mytable">
                        <thead>
                            <tr>
                                <th valign="middle">#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th colspan="3">Actions</th>
                            </tr>
                            {{ csrf_field() }}
                        </thead>
                        <tbody>
                            @foreach($usuarios as $indexKey => $usu)
                            <tr class="item{{$usu->id}}">
                                <td class="col1">{{ $indexKey+1 }}</td>
                                <td>{{$usu->name}}</td>
                                <td>
                                    {{$usu->email}}
                                </td>                                                                    
                                <td>
                                  <a href="{{ route('users.show', $usu->id) }}" class="btn btn-primary" data-toggle="tooltip" title="Show"><i class="fa fa-eye"></i>

                                  </a>
                              </td>  
                              
                              <td>
                                  <a href="{{ route('users.edit', $usu->id) }}" class="btn btn-warning" data-toggle="tooltip" title="Update"><i class="fa fa-pencil"></i>
                                  </a>
                              </td>  

                              <td>
                                  <form action="{{ route('users.destroy', $usu->id) }}" method="post">
                                    <input name="_method" type="hidden" value="DELETE">
                                    <input required="true" type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button type="submit" onclick="if(!confirm('¿Desea eliminar al analista?'))event.preventDefault();" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i class="fa fa-trash"></i></button>

                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div><!-- /.panel-body -->
        </div><!-- /.panel panel-default -->
    </div><!-- /.col-md-8 -->
</section><!-- /.content -->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function() {
        $('#mytable').dataTable();
    } );    
</script> 

</body>
</div>  
<!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/usuarios/respaldo.blade.php
@include('layouts.headuser')

<div class="page-content-wrapper">
    <div class="page-content">                    
    <section class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
			<iframe src="http://localhost/Zogan_Systems/public/respaldo/" width="800" height="600" frameborder="0"></iframe>
        </div>
    </div>
</div>
</section>
</div>
</div>
@include('layouts.footer')                

resources/views/usuarios/see.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            </head>

            <body>

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">

                            <hr>
                            <a class="btn btn-default btn-teal btn-responsive" style="float: right;" href="javascript:history.back(1)" title="Regresar"><i class="fa fa-mail-reply-all fa-lg"></i></a><br>                 
                            <div class="panel panel-default">
                                <center><div class="panel-heading"><h4>User</h4></div></center>
                                <div class="panel-body">
                    <form method="post" action=" {{ url('/usuarios/') }}/{{ $usuarios->id }}">
                        <input name="_method" type="hidden" value="PUT">
                        <input required="true" type="hidden" name="_token" value="{{ csrf_token() }}">
                        <div class="form-group col-xs-6">
                            <label for="name" class="col-md-4 control-label">Name</label>

                                <input id="name" type="text" class="form-control" placeholder="Indique el nombre" name="name" value="{{ $usuarios->name }}" required autofocus disabled>
                        </div>

                        <div class="form-group col-xs-6">
                            <label for="email" class="col-md-4 control-label">E-mail</label>

                                <input id="email" type="email" class="form-control" placeholder="Indique el correo electrónico" name="email" value="{{ $usuarios->email }}" required disabled>

                        </div>    


                                 
                                </center>
                                <div class="col-md-10 col-md-offset-1">
                              <h3>Permits</h3>
                              <p>Section the functions to which the user will have access</p>            
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>Module / Permission</th>
                                    <th></th>
                                  </tr>
                                </thead>
                                <tbody>
                                @foreach ($modules as $mod)
                                  <tr>
                                    <td>{{ ($mod->nombre) }}</td>
                                    <td>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" 
                                                   value="{{ ($mod->id) }}" 
                                                   name="modules[]"
                                                   disabled="true" 
                                                    @if (in_array($mod->id, $checked ))
                                                        {{ 'checked' }}
                                                    @endif  
                                            ></label>
                                    </div>
                                    </td>
                                  </tr>
                                @endforeach
                                </tbody>
                              </table>
                            </div> 
                               <center class="col-xs-offset-3 col-xs-6">
                                      <button data-toggle="tooltip" title="Regresar" type="reset" onClick="javascript:history.go(-1);" class="btn btn-refresh margin glyphicon glyphicon-arrow-left"></button>
                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- jQuery -->
                <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>

            </body>
        </div>  
    <!-- /.content-wrapper -->

@include('layouts.footer')

resources/views/usuarios/seguridad.blade.php
@include('layouts.head')

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

<header class="main-header">
@include('layouts.header')
</header>

@include('layouts.menu')

    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            </head>

            <body>

<div class="col-md-10">
@if(Session::get('message'))
<div class="col-md-6 col-md-offset-6" style="margin-top: 5px;">
  <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h3> {{ Session::get('message') }}</h3>
</div>
</div>
@endif                            
</div> 

                   
    <section class="content">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <hr>
                <a class="btn btn-default btn-teal btn-responsive" style="float: right;" href="javascript:history.back(1)" title="Regresar"><i class="fa fa-mail-reply-all fa-lg"></i></a><br><br><br><br>                  
                <div class="panel panel-default">
                    <center>
                        <div class="panel-heading"><h4>Update User</h4></div>
                    </center>
                    
                    <div class="panel-body">
                        <form method="post" action=" {{ url('/cambio_clave') }}" class="form-horizontal" role="form">
                         <input name="_method" type="hidden" value="PUT">
                         <input required="true" type="hidden" name="_token" value="{{ csrf_token() }}">


                         <div class="form-group{{ Session::get('vieja') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Current Password</label>

                            <div class="col-md-6">
                                <input id="vieja" type="password" placeholder="Contraseña actual" class="form-control" name="vieja" required>

                               @if(Session::get('vieja'))
                                <span class="help-block">
                                    <strong> {{ Session::get('vieja') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">New Password
                            </label>

                            <div class="col-md-6">
                                <input id="password" type="password" placeholder="Nueva Contraseña" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm New Password
                            </label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" placeholder="Repita su contraseña" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <center>                                      
                                    <button data-toggle="tooltip" title="Guardar" type="submit" class="btn btn-guardar margin glyphicon glyphicon-floppy-disk" name="agregar"></button>
                                </center>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

@include('layouts.footer')                